#!/usr/bin/env node

var fs = require('fs');
var iterateOnFile = require('./iterator.js').iterateOnFile;

var query = JSON.parse(process.argv[3]);
var queryKeys = Object.keys(query);

var recordsUpdated = 0;

var tempFile = fs.createWriteStream(process.argv[2] + '.temp');

var removeToTemp = function remove (record) {
    var recordMatched = true;

    for( j=0; j < queryKeys.length; j++ ){
        recordMatched &= (query[queryKeys[j]] == record[queryKeys[j]])
    }

    if ( !recordMatched ) {
        tempFile.write(JSON.stringify(record) + '\n');
    } else {
        recordsUpdated += 1;
    }
};

var writeChanges = function writeChanges () {
    tempFile.end();
    fs.rename(process.argv[2] + '.temp', process.argv[2], function () {
        process.stdout.write('Deleted ' + recordsUpdated + ' records.');
    });
};

iterateOnFile( removeToTemp, writeChanges );
