#!/usr/bin/env node

var fs = require('fs');

var libdb = require('./libdb.js')
var iterateOnFile = libdb.iterateOnFile;
var recordMatched = libdb.recordMatched;

var query = eval('(' + process.argv[3] + ')');

var recordsUpdated = 0;

var tempFile = fs.createWriteStream(process.argv[2] + '.temp');

var removeToTemp = function remove (record) {

    if ( !recordMatched(record, query) ) {
        tempFile.write(JSON.stringify(record) + '\n');
    } else {
        recordsUpdated += 1;
    }
};

var writeChanges = function writeChanges () {
    tempFile.end();
    fs.rename(process.argv[2] + '.temp', process.argv[2], function () {
        process.stdout.write('Deleted ' + recordsUpdated + ' records.');
    });
};

iterateOnFile( removeToTemp, writeChanges );
