#!/usr/bin/env node

var iterateOnFile = require('./iterator.js').iterateOnFile;

var query = JSON.parse(process.argv[3]);
var queryKeys = Object.keys(query);

var find = function find (record) {
    var recordMatched = true;

    for( j=0; j < queryKeys.length; j++ ){
        if (typeof(query[queryKeys[j]]) === 'string') {
            recordMatched &= (query[queryKeys[j]] == record[queryKeys[j]])
        } else if (query[queryKeys[j]]['$ne']) {
            recordMatched &= (query[queryKeys[j]]['$ne'] != record[queryKeys[j]])
        }
    }

    if ( recordMatched ) {
        process.stdout.write(JSON.stringify(record) + '\n');
    }
};

iterateOnFile( find );
