#!/usr/bin/env bash

dbfile=$1

if [ ! -f $dbfile ]
then
  echo "error: $dbfile db file does not exist!"
  exit 1
fi

if ! test -t 0 ; then
    xargs -0 echo >> $dbfile
else
    records=$2
    echo $records >> $dbfile
fi
