#!/usr/bin/env node

var fs = require('fs');
var iterateOnFile = require('./iterator.js').iterateOnFile;

var query = JSON.parse(process.argv[3]);
var queryKeys = Object.keys(query);

var updates = JSON.parse(process.argv[4]);
var updatesKeys = Object.keys(updates);

var tempFile = fs.createWriteStream(process.argv[2] + '.temp');
var recordsUpdated = 0;

var updateTempFile = function updateTempFile (record) {
    var recordMatched = true;

    for( j=0; j < queryKeys.length; j++ ){
        recordMatched &= (query[queryKeys[j]] == record[queryKeys[j]])
    }

    if ( recordMatched ) {
        updatesKeys.forEach( function (key) {
            record[key] = updates[key];
        });
        recordsUpdated += 1;
    }

    tempFile.write(JSON.stringify(record) + '\n');
};

var writeChanges = function writeChanges () {
    tempFile.end();
    fs.rename(process.argv[2] + '.temp', process.argv[2], function () {
        process.stdout.write('Updated ' + recordsUpdated + ' records.');
    });
};

iterateOnFile( updateTempFile, writeChanges );
